syntax on
set spell
set number
set relativenumber
set clipboard=unnamedplus
set background=dark
set nohlsearch
set cc=80
set statusline+=%f\ %h%m%r%=\ %{FugitiveStatusline()}\ %y\ [%{&encoding}]\ \ %-8.(%l,%c%)\ %P


" case insensitive searching
set ignorecase

" lower case search case insensitive; if upper case exists, case sensitive; used with set ignorecase
set smartcase

" expand tab input with spaces
set expandtab

" spaces per tab
set tabstop=4

" spaces per indentation level
set shiftwidth=4

" aware indentations for newline insert
set smartindent

" set cursorcolumn
set cursorline

" set space as leader key
let mapleader=" "

" toggle spell check, this line must be under the leader key defination line
" <CR> means carriage return
map <leader>s :set spell!<CR>

" toggle cursorcolumn
map <leader>c :set cursorcolumn!<CR>

" split movement
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" split resize
map <C-,> <C-w><
map <C-.> <C-w>>
map <C-=> <C-w>=
map <C--> <C-w>-

" split open
map <leader>x :split<CR>
map <leader>v :vsplit<CR>

" automatically run xrdb when Xresources are updated
autocmd BufWritePost ~/.Xresources !xrdb %
